version: '3.8'

services:
  app:
    build: .
    image: zeronauta/analisador-de-curriculo:latest
    container_name: analisador_de_curriculo_app
    restart: always
    env_file:
      - ./.env
    # Conecta o serviço à rede externa definida abaixo
    networks:
      - proxy-network

# Informa ao Docker que 'proxy-network' é uma rede existente
networks:
  proxy-network:
    external: true