version: '3.8'

# Define a rede interna para a aplicação
networks:
  app-network:
    driver: bridge

services:
  # 1. Nosso aplicativo Analisador de Currículo
  app:
    build: .
    image: zeronauta/analisador-de-curriculo:latest
    container_name: analisador_de_curriculo_app
    restart: always
    env_file:
      - ./.env # Carrega a chave da API
    networks:
      # Conecta o container à rede interna
      - app-network
    # NENHUMA PORTA EXPOSTA PARA O HOST!
